backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    identifier_field: 'permalink'
    label: 'Blog'
    folder: 'src/pages/blog'
    create: true
    slug: '{{permalink}}'
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'blog-post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Permalink', name: 'permalink', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Featured Image', name: 'thumbnail', widget: image, required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'banner', name: 'banner', widget: image, required: false }
